### ISSUE TITLE
add support for downloading content from egnyte.com file sharing

### ISSUE THREAD

**Issue by asch-id** [IntegralDefense/ACE#186]
link in email is in this format - https://infoserver10.egnyte.com/dl/fwY0DwmPPP
to download the content - dl/dd -> https://infoserver10.egnyte.com/dd/fwY0DwmPPP

**Comment by seanmcfeely** [comment]
https://ace.integraldefense.com/ace/analysis?direct=7f1b26d4-4b0f-495e-a980-d2c4986d90af
