### ISSUE TITLE
Fix "hidden" alert tags from showing up as white text with transparent background

### ISSUE THREAD

**Issue by automationator** [IntegralDefense/ACE#2]
The Events page still shows hidden tags (e.g.: mail_from, mail_to, delivered_to, etc) with a transparent background and white text. They're not quite hidden.

**Comment by seanmcfeely** [comment]
Fixed by this commit - https://github.com/IntegralDefense/ACE/commit/b1becc35ff27e3156037b1ec4d41cce64f3cffd1
