### ISSUE TITLE
Remediating a group of email alerts where one has a null address causes failure

### ISSUE THREAD

**Issue by seanmcfeely** [IntegralDefense/ACE#65]
If you group a bunch of email alerts together and one or more of those alerts have a null email address (no recipient email address to work with, such as the undeliverable alerts -- example - https://ace.local/saq/analysis?direct=9f10fe49-14a4-46fe-bbdb-ee48b7796f80)

The correct way this should work: One of these ACE alerts should not cause all of the selected ACE alerts to fail remediating.

**Comment by KarmaPenny** [comment]
Is the recipient showing as none also a bug. In the example you gave I feel like the recipient should be <jcemmeryoww@outlook.com> not none.
